[package]
name = "octopus_server"
version = "0.9.24"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argon2 = "0.5.3"
async-openai = "0.23.4"
async-recursion = "1.1.1"
axum = { version = "0.7.5", features = ["multipart", "ws"] }
axum-extra = { version = "0.9.3", features = ["typed-header"] }
axum-macros = "0.4.1"
base64 = "0.22.1"
bytesize = "1.3.0"
clap = { version = "4.5.9", features = ["derive", "env"] }
chrono = { version = "0.4.38", features = ["serde"] }
diff = "0.1.13"
fake = "2.9.2"
fantoccini = "0.21.0"
futures = "0.3.30"
futures-util = { version = "0.3.30", default-features = false, features = ["sink", "std"] }
hex = "0.4.3"
http = "1.1.0"
http-body = "1.0.0"
http-body-util = "0.1.2"
hyper = { version = "1.4.1", features = ["full"] }
infer = "0.16.0"
mime = "0.3.17"
num_cpus = "1.16.0"
once_cell = "1.19.0"
port-selector = "0.1.6"
rand = "0.8.5"
rand_core = { version = "0.6.4", features = ["std"] }
regex = "1.10.5"
reqwest = { version = "0.12.5", features = ["json"] }
rev_buf_reader = "0.3.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
sha3 = "0.10.8"
sqlx = { version = "0.7.4", features = [
    "chrono",
    "json",
    "postgres",
    "runtime-tokio-rustls",
    "uuid",
] }
strum_macros = "0.26.4"
systemstat = "0.2.3"
tempfile = "3.10.1"
tokio = { version = "1.38.0", features = ["rt-multi-thread", "time"] }
tokio-tungstenite = { path = "crates/tokio-tungstenite" }
tower = { version = "0.4.13", features = ["timeout", "util"] }
tower-http = { version = "0.5.2", features = [
    "add-extension",
    "cors",
    "fs",
    "limit",
    "trace",
] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
utoipa = { version = "4.2.3", features = ["axum_extras", "chrono", "uuid"] }
utoipa-swagger-ui = { version = "7.1.0", features = ["axum"] }
uuid = { version = "1.10.0", features = ["serde", "v4"] }
walkdir = "2.5.0"
validator = { version = "0.18.1", features = ["derive"] }
zip = "2.1.3"

[profile.release]
lto = true
opt-level = "z"
panic = "abort"
strip = true
