[package]
name = "octopus_server"
version = "0.4.0-pre"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argon2 = "0.5"
async-openai = "0.17"
axum = { version = "0.7", features = ["multipart"] }
axum-macros = "0.4"
base64 = "0.21"
bytesize = "1.3"
clap = { version = "4.4", features = ["derive", "env"] }
chrono = { version = "0.4", features = ["serde"] }
fake = "2.9"
http = "1.0"
http-body = "1.0"
http-body-util = "0.1"
hyper = { version = "1.0", features = ["full"] }
infer = "0.15"
mime = "0.3"
num_cpus = "1.16"
rand = "0.8"
rand_core = { version = "0.6", features = ["std"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.7", features = [
    "chrono",
    "json",
    "postgres",
    "runtime-tokio-rustls",
    "uuid",
] }
strum_macros = "0.25"
systemstat = "0.2"
tokio = { version = "1.34", features = ["full"] }
tower = { version = "0.4", features = ["timeout", "util"] }
tower-http = { version = "0.5", features = ["add-extension", "cors", "fs", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
utoipa = { version = "4.1", features = ["axum_extras", "chrono", "uuid"] }
utoipa-swagger-ui = { version = "5.0", features = ["axum"] }
uuid = { version = "1.6", features = ["serde", "v4"] }
validator = { version = "0.16", features = ["derive"] }
