[package]
name = "octopus_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argon2 = "0.5"
async-openai = "0.13"
axum = { version = "0.6", features = ["multipart"] }
axum-macros = "0.3"
base64 = "0.21"
clap = { version = "4.3", features = ["derive", "env"] }
chrono = { version = "0.4", features = ["serde"] }
fake = "2.7"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
#hyper-multipart-rfc7578 = "0.8"
mime = "0.3"
rand = "0.8"
rand_core = { version = "0.6", features = ["std"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.7", features = [
    "chrono",
    "json",
    "postgres",
    "runtime-tokio-rustls",
    "uuid",
] }
strum_macros = "0.25"
tokio = { version = "1.32", features = ["full"] }
tower = { version = "0.4", features = ["timeout", "util"] }
tower-http = { version = "0.4", features = ["add-extension", "cors", "fs", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
utoipa = { version = "3.4", features = ["axum_extras", "chrono", "uuid"] }
utoipa-swagger-ui = { version = "3.1", features = ["axum"] }
uuid = { version = "1.4", features = ["serde", "v4"] }
validator = { version = "0.16", features = ["derive"] }
