[package]
name = "octopus_server"
version = "0.8.25"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argon2 = "0.5"
async-openai = "0.21"
async-recursion = "1.1"
axum = { version = "0.7", features = ["multipart", "ws"] }
axum-extra = { version = "0.9", features = ["typed-header"] }
axum-macros = "0.4"
base64 = "0.22"
bytesize = "1.3"
clap = { version = "4.5", features = ["derive", "env"] }
chrono = { version = "0.4", features = ["serde"] }
fake = "2.9"
fantoccini = "0.20.0-rc.7"
futures = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
http = "1.1"
http-body = "1.0"
http-body-util = "0.1"
hyper = { version = "1.3", features = ["full"] }
infer = "0.15"
mime = "0.3"
num_cpus = "1.16"
port-selector = "0.1"
rand = "0.8"
rand_core = { version = "0.6", features = ["std"] }
regex = "1.10"
reqwest = { version = "0.12", features = ["json"] }
rev_buf_reader = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.7", features = [
    "chrono",
    "json",
    "postgres",
    "runtime-tokio-rustls",
    "uuid",
] }
strum_macros = "0.26"
systemstat = "0.2"
tempfile = "3.10"
tokio = { version = "1.37", features = ["rt-multi-thread", "time"] }
tokio-tungstenite = { path = "crates/tokio-tungstenite" }
tower = { version = "0.4", features = ["timeout", "util"] }
tower-http = { version = "0.5", features = ["add-extension", "cors", "fs", "limit", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
utoipa = { version = "4.2", features = ["axum_extras", "chrono", "uuid"] }
utoipa-swagger-ui = { version = "7.0", features = ["axum"] }
uuid = { version = "1.8", features = ["serde", "v4"] }
walkdir = "2.5"
validator = { version = "0.18", features = ["derive"] }
zip = "1.2"

[profile.release]
lto = true
opt-level = "z"
panic = "abort"
strip = true
