-- Add migration script here

UPDATE parameters SET name = 'MAIN_LLM_AZURE_OPENAI_API_KEY' WHERE name = 'AZURE_OPENAI_API_KEY';
UPDATE parameters SET name = 'MAIN_LLM_AZURE_OPENAI_DEPLOYMENT_ID' WHERE name = 'AZURE_OPENAI_DEPLOYMENT_ID';
UPDATE parameters SET name = 'MAIN_LLM_AZURE_OPENAI_ENABLED' WHERE name = 'AZURE_OPENAI_ENABLED';
UPDATE parameters SET name = 'MAIN_LLM_OPENAI_API_KEY' WHERE name = 'OPENAI_API_KEY';
UPDATE parameters SET name = 'MAIN_LLM_OPENAI_MODEL' WHERE name = 'AI_MODEL';
UPDATE parameters SET name = 'MAIN_LLM_SYSTEM_PROMPT' WHERE name = 'AI_SYSTEM_PROMPT';
